### ISSUE TITLE
scripts/download_deps.sh: downloading archives

### ISSUE THREAD

**Issue by plowsof** [Elite-Labs/EliteWallet#7]
*edit* - elite wallet have clarified that the script is used for development purposes only for speeding up and NOT mentioned in the build process description. 

* suggestion would be to add this as a disclaimer at the top of the file in comments to avoid confusion 
---

**Comment by Elite-Labs** [comment]
@plowsof Thanks for the suggestion. Disclaimer was added at the beginning of download_deps.sh file.
